#!/usr/bin/env node
/**
 * Stores the prototype's flows, one file per product section, desktop and mobile.
 *
 * A wired template says where each link goes; this reads that ledger
 * (design-kit/templates/_prototype.json, written by scripts/wire-prototype.mjs) and the
 * hotspot rules, and writes for every section in scripts/lib/consumer-prototype.mjs:
 *
 *   design-kit/flows/<section>.json   entries per platform, screens, transitions
 *                                     (same shape as the deliverables' flows.json,
 *                                     with the trigger spelled out instead of a node id)
 *   design-kit/flows/index.html       the human-readable map: start points, every
 *                                     screen, every transition, what is missing here
 *
 * The agency portal keeps its generated flow in
 * design-kit/deliverables/agency-portal/flows.json (scripts/build-portal-flows.py); the
 * index links to it so every section is reachable from one page.
 *
 *   npm run build:flows            (also runs as part of npm run build:templates)
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SECTIONS, sectionOf } from './lib/consumer-prototype.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TEMPLATES = join(ROOT, 'design-kit/templates');
const OUT = join(ROOT, 'design-kit/flows');
const PLATFORM = { desktop: 'web-desktop', mobile: 'web-mobile' };

const manifest = JSON.parse(readFileSync(join(TEMPLATES, '_prototype.json'), 'utf8'));
const { templates } = JSON.parse(readFileSync(join(TEMPLATES, 'live-templates.json'), 'utf8'));
const today = new Date().toISOString().slice(0, 10);
mkdirSync(OUT, { recursive: true });

const DIALOG = /^(login-dialog|login|dpv-phone|dpv-report|dpv-report-in|dpv-report-form|save-search|dpv-gallery)$/;
const MENU = /^(menu-[\w-]+|sort-menu|location-dropdown|search-suggestions|user-menu)$/;
const kindOf = (page) => (DIALOG.test(page) ? 'dialog' : MENU.test(page) ? 'menu' : page === 'm-filters' ? 'sheet' : page === 'dpv-details-expanded' ? 'state' : 'page');
const labelOf = (page) => templates[page]?.label || page;
const idOf = (layout, page) => (layout === 'mobile' ? `m-${page}` : page);
const hotspotKind = (h) => (h.hover ? 'hover' : h.key ? 'escape' : h.outside ? 'click-outside' : h.event && h.event !== 'click' ? h.event : 'click');
const hotspotTrigger = (h) => {
  if (h.text) return { text: h.text, ...(h.band ? { band: h.band } : {}) };
  if (h.hover) return { hover: h.hover, ...(h.band ? { band: h.band } : {}) };
  if (h.selector) return { selector: h.selector, ...(h.event ? { event: h.event } : {}) };
  if (h.outside) return { outside: h.outside };
  if (h.box) return { box: h.box };
  if (h.key) return { key: h.key };
  return {};
};

const sectionFiles = [];
for (const [id, section] of Object.entries(SECTIONS)) {
  if (section.portal) continue;
  const flow = {
    _purpose: `Generated by scripts/build-flows.mjs from the wired templates. The ${section.label} section of the dubizzle Egypt consumer prototype: where each screen leads, per platform. Re-run npm run build:flows after npm run wire:prototype.`,
    section: id,
    label: section.label,
    generated: today,
    entries: {},
    screens: {},
    unavailable: [],
    transitions: [],
  };
  for (const layout of ['desktop', 'mobile']) {
    const pages = manifest.layouts[layout];
    const platform = PLATFORM[layout];
    const entryFile = join(TEMPLATES, layout, `${section.entry}.html`);
    if (existsSync(entryFile)) flow.entries[platform] = idOf(layout, section.entry);
    for (const page of section.pages) {
      const file = join(TEMPLATES, layout, `${page}.html`);
      if (!existsSync(file)) {
        const t = templates[page];
        const reason = !t
          ? 'hand-built page, not captured on this layout'
          : t.account
            ? 'account template: built from a redacted logged-in capture on the capturing machine — not committed yet (tracked since 2026-10-06; commit it from the Mac after npm run check:prototype)'
            : layout === 'mobile' && /^(menu-|location-dropdown|search-suggestions|login-dialog|sort-menu|save-search|dpv-phone|dpv-gallery|user-menu)/.test(page)
              ? 'desktop-only state (mobile has its own page for it, or it was not captured on mobile)'
              : layout === 'desktop' && /^m-/.test(page)
                ? 'mobile-only page'
                : 'not captured on this layout';
        flow.unavailable.push({ page, platform, reason });
        continue;
      }
      const entry = pages[page];
      flow.screens[idOf(layout, page)] = { page, platform, kind: kindOf(page), label: labelOf(page), file: `templates/${layout}/${page}.html` };
      if (!entry) continue;
      for (const [target, l] of Object.entries(entry.links)) {
        const t = { from: idOf(layout, page), to: idOf(layout, target), kind: 'link', trigger: { links: l.count, texts: l.texts }, count: l.count };
        if (l.representative) t.representative = l.representative;
        const ts = sectionOf(target);
        if (ts && ts !== id) t.exit = ts;
        flow.transitions.push(t);
      }
      for (const h of entry.hotspots) {
        const t = { from: idOf(layout, page), to: idOf(layout, h.go), kind: hotspotKind(h), trigger: hotspotTrigger(h), count: 1 };
        const ts = sectionOf(h.go);
        if (ts && ts !== id) t.exit = ts;
        flow.transitions.push(t);
      }
    }
  }
  // exits land on screens outside this file; name them so a reader can follow
  const named = new Set(Object.keys(flow.screens));
  flow.exits = {};
  for (const t of flow.transitions) {
    if (!named.has(t.to)) {
      const page = t.to.replace(/^m-/, '');
      const layout = t.to.startsWith('m-') ? 'mobile' : 'desktop';
      flow.exits[t.to] = { page, platform: PLATFORM[layout], section: sectionOf(page), label: labelOf(page), file: `templates/${layout}/${page}.html` };
    }
  }
  flow.summary = {
    screens: Object.keys(flow.screens).length,
    transitions: flow.transitions.length,
    exits: Object.keys(flow.exits).length,
    unavailable_here: flow.unavailable.length,
  };
  writeFileSync(join(OUT, `${id}.json`), JSON.stringify(flow, null, 1) + '\n');
  sectionFiles.push(flow);
  console.log(`flow ${id.padEnd(14)} ${String(flow.summary.screens).padStart(3)} screens · ${String(flow.summary.transitions).padStart(4)} transitions · ${flow.summary.exits} exits · ${flow.summary.unavailable_here} not built here`);
}

// ── Agency portal: reference the generated deliverable flow ───────────────────
let portal = null;
const portalFlowFile = join(ROOT, 'design-kit/deliverables/agency-portal/flows.json');
if (existsSync(portalFlowFile)) {
  const f = JSON.parse(readFileSync(portalFlowFile, 'utf8'));
  portal = { screens: Object.keys(f.screens).length, transitions: f.transitions.length, file: 'deliverables/agency-portal/flows.json' };
}

// ── Index page ───────────────────────────────────────────────────────────────
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
const describeTrigger = (t) => {
  const tr = t.trigger;
  if (t.kind === 'link') return `${t.count} link${t.count === 1 ? '' : 's'}${tr.texts?.length ? ` — “${tr.texts.map(esc).join('”, “')}”` : ''}`;
  if (tr.text) return `click “${esc(tr.text)}”`;
  if (tr.hover) return `hover “${esc(tr.hover)}”`;
  if (tr.selector) return `${tr.event || 'click'} <code>${esc(tr.selector)}</code>`;
  if (tr.outside) return 'click outside the panel';
  if (tr.box) return `tap the top-left control (back / close)`;
  if (tr.key) return `press ${tr.key}`;
  return t.kind;
};
const sectionHtml = (flow) => {
  const screens = Object.entries(flow.screens);
  const byPlatform = (p) => screens.filter(([, s]) => s.platform === p);
  const screenList = (p) => byPlatform(p).map(([id, s]) => `<li><a href="../${s.file}">${esc(s.label)}</a> <span class="muted">${s.kind} · <code>${id}</code></span></li>`).join('') || '<li class="muted">none built on this layout</li>';
  const rows = flow.transitions
    .map((t) => `<tr><td><code>${esc(t.from)}</code></td><td><code>${esc(t.to)}</code>${t.exit ? ` <span class="pill pill--regular">→ ${esc(SECTIONS[t.exit]?.label || t.exit)}</span>` : ''}</td><td>${describeTrigger(t)}${t.representative ? `<br><span class="muted">representative: ${esc(t.representative)}</span>` : ''}</td></tr>`)
    .join('\n');
  const start = Object.entries(flow.entries).map(([p, id]) => `<a class="btn btn--primary btn--sm" href="../${flow.screens[id].file}">Start · ${p === 'web-desktop' ? 'desktop' : 'mobile'}</a>`).join(' ');
  const missing = flow.unavailable.length
    ? `<details><summary>${flow.unavailable.length} screen(s) of this section are not built in this clone</summary><ul>${flow.unavailable.map((u) => `<li><code>${esc(u.page)}</code> (${u.platform}) — ${esc(u.reason)}</li>`).join('')}</ul></details>`
    : '';
  return `<section id="${flow.section}">
  <h2>${esc(flow.label)} <span class="muted">${flow.summary.screens} screens · ${flow.summary.transitions} transitions</span></h2>
  <p>${start} <a class="btn btn--secondary btn--sm" href="${flow.section}.json">flows.json</a></p>
  <div class="cols"><div><h3>Desktop</h3><ul>${screenList('web-desktop')}</ul></div><div><h3>Mobile</h3><ul>${screenList('web-mobile')}</ul></div></div>
  ${missing}
  <details><summary>All ${flow.transitions.length} transitions</summary>
  <table><thead><tr><th>From</th><th>To</th><th>Trigger</th></tr></thead><tbody>
${rows}
  </tbody></table></details>
</section>`;
};

const totals = sectionFiles.reduce((a, f) => ({ screens: a.screens + f.summary.screens, transitions: a.transitions + f.summary.transitions }), { screens: 0, transitions: 0 });
writeFileSync(
  join(OUT, 'index.html'),
  `<!doctype html>
<!-- GENERATED by scripts/build-flows.mjs — do not edit; run npm run build:flows -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Prototype flows — dubizzle Egypt</title>
<link rel="stylesheet" href="../tokens/tokens.css"><link rel="stylesheet" href="../patterns/patterns.css">
<style>
  body { background: var(--surface-subtle); }
  .wrap { max-width: 110rem; margin-inline: auto; padding: var(--space-6); }
  .lede { color: var(--text-secondary); max-width: 80rem; margin: var(--space-2) 0 var(--space-6); }
  section { background: var(--surface-card); border-radius: var(--radius-lg); padding: var(--space-5) var(--space-6); margin-bottom: var(--space-6); }
  h2 { margin: 0 0 var(--space-3); } h2 .muted { font-weight: 400; font-size: var(--text-sm); }
  h3 { font-size: var(--text-sm); text-transform: uppercase; color: var(--text-tertiary); margin: var(--space-4) 0 var(--space-2); }
  .cols { display: grid; grid-template-columns: 1fr 1fr; gap: var(--space-6); } @media (max-width: 720px) { .cols { grid-template-columns: 1fr; } }
  ul { margin: 0; padding-inline-start: var(--space-4); } li { margin: var(--space-1) 0; }
  table { width: 100%; border-collapse: collapse; margin-top: var(--space-3); }
  th, td { text-align: left; padding: var(--space-2) var(--space-3); border-bottom: 1px solid var(--border-default); vertical-align: top; font-size: var(--text-sm); }
  th { font-size: var(--text-xs); text-transform: uppercase; color: var(--text-tertiary); }
  .muted { color: var(--text-tertiary); font-size: var(--text-xs); }
  code { font-size: 0.9em; }
  summary { cursor: pointer; margin-top: var(--space-3); color: var(--text-secondary); }
  nav.toc a { margin-inline-end: var(--space-4); }
</style></head>
<body><div class="wrap">
  <h1 class="page-head__title">Prototype flows</h1>
  <p class="lede">
    The captured screens linked into a clickable prototype — desktop and mobile web — stored by product section.
    Every link on a template leads to the template it would open on live (or says “Not part of this prototype”),
    and the dropdowns, dialogs and sheets open from the control that opens them on live. A <em>representative</em>
    jump lands on the one captured example of that screen type (every car ad opens the captured car ad).
    Generated ${today} · ${sectionFiles.length} consumer sections · ${totals.screens} screens · ${totals.transitions} transitions${portal ? ` · agency portal ${portal.screens} screens / ${portal.transitions} transitions` : ''}.
  </p>
  <nav class="toc lede">${sectionFiles.map((f) => `<a href="#${f.section}">${esc(f.label)}</a>`).join('')}<a href="#agency-portal">Agency portal</a></nav>
${sectionFiles.map(sectionHtml).join('\n')}
<section id="agency-portal">
  <h2>${esc(SECTIONS['agency-portal'].label)}${portal ? ` <span class="muted">${portal.screens} screens · ${portal.transitions} transitions</span>` : ''}</h2>
  <p><a class="btn btn--primary btn--sm" href="../templates/desktop/portal-dashboard.html">Start · desktop</a> ${portal ? `<a class="btn btn--secondary btn--sm" href="../${portal.file}">flows.json</a>` : ''}</p>
  <p class="lede">Desktop only — dubizzle Pro has no mobile layout. Wired by <code>scripts/lib/prototype.mjs</code>; its flow is generated by <code>scripts/build-portal-flows.py</code> and lives with the deliverable. The portal's templates come from a logged-in account and are built only on the capturing machine.</p>
</section>
  <p class="lede"><a href="../index.html">← Design system</a> · <a href="../templates/index.html">Page templates</a></p>
</div></body></html>
`,
);
console.log(`\ndesign-kit/flows/index.html · ${sectionFiles.length} section files`);
